import UIKit

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// Project Euler # 2

var total = 0
var totalEvenNumber = 0
var arr = [Int]()

for i in 1...32 {
    if i > 2 {
        let count = arr.count
        total = arr[count-1] + arr[count-2]
        arr.append(total)
    } else {
        arr.append(i)
    }
}

for x in arr {
    if x % 2 == 0 {
        totalEvenNumber += x
    }
}
print(totalEvenNumber) // Total sum of the even numbers = 4613732









